In [1]:
import torch

In [2]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [3]:
h


tensor([[9., 8., 2.],
        [2., 6., 2.],
        [3., 3., 9.]])

In [4]:
torch.inverse(h)

tensor([[ 0.1538, -0.2115,  0.0128],
        [-0.0385,  0.2404, -0.0449],
        [-0.0385, -0.0096,  0.1218]])

In [ ]:
torch.log(h)

tensor([[2.1972, 2.0794, 0.6931],
        [0.6931, 1.7918, 0.6931],
        [1.0986, 1.0986, 2.1972]])

In [ ]:
h

In [ ]:
torch.min(e)